const $=id=>document.getElementById(id);let clips=[];let current=null;let manual=false;
const fmt=s=>{s=Math.max(0,Math.floor(Number(s)||0));let h=Math.floor(s/3600),m=Math.floor(s%3600/60),x=s%60;return h?String(h).padStart(2,'0')+':'+String(m).padStart(2,'0')+':'+String(x).padStart(2,'0'):String(m).padStart(2,'0')+':'+String(x).padStart(2,'0')};
const parse=s=>{s=String(s).trim();if(/^\d+(\.\d+)?$/.test(s))return +s;let p=s.split(':').map(Number);return p.length===2&&p.every(Number.isFinite)?p[0]*60+p[1]:p.length===3&&p.every(Number.isFinite)?p[0]*3600+p[1]*60+p[2]:NaN};
async function tab(){return (await chrome.tabs.query({active:true,currentWindow:true}))[0]||null}
async function msg(m){let t=await tab();if(!t||!/youtube\.com/.test(t.url||''))throw Error('NO_YT');return chrome.tabs.sendMessage(t.id,m)}
function toast(x){$('toast').textContent=x;$('toast').classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>$('toast').classList.remove('show'),1800)}
async function load(){clips=(await chrome.storage.local.get({clips:[]})).clips||[];render()}
async function info(){try{let x=await msg({action:'GET_VIDEO_INFO'});current=x;if(x.isWatchPage){$('title').textContent=x.title;$('time').textContent=fmt(x.currentTime);$('duration').textContent=Number.isFinite(x.duration)?'Duration '+fmt(x.duration):'Duration —';$('thumb').innerHTML='<img src="https://img.youtube.com/vi/'+x.videoId+'/hqdefault.jpg">';$('hint').textContent='Capture the current moment or enter timestamps manually.';if(!manual){$('start').value='00:00';$('end').value=Number.isFinite(x.duration)?fmt(Math.min(x.duration,10)):'00:10'}}else throw Error()}catch{$('title').textContent='Open a YouTube video';$('hint').textContent='This extension works on YouTube watch pages.';current=null}}
async function save(){let a=parse($('start').value),b=parse($('end').value),n=$('name').value.trim();if(!current?.videoId)return toast('Open a YouTube video first');if(!Number.isFinite(a)||!Number.isFinite(b)||b<=a||!n)return toast('Enter a valid range and clip name');clips.unshift({id:crypto.randomUUID(),videoId:current.videoId,videoTitle:current.title,clipName:n,startTime:a,endTime:b,createdAt:Date.now()});await chrome.storage.local.set({clips});$('name').value='';manual=false;render();toast('Clip saved')}
function render(){let q=$('search').value.toLowerCase(),arr=clips.filter(c=>(c.clipName+' '+c.videoTitle).toLowerCase().includes(q));if($('sort').value==='name')arr.sort((a,b)=>a.clipName.localeCompare(b.clipName));if($('sort').value==='video')arr.sort((a,b)=>a.videoTitle.localeCompare(b.videoTitle));$('count').textContent=clips.length;$('list').innerHTML=arr.map(c=>'<article class="clip"><div class="clipTitle">'+esc(c.clipName)+'</div><div class="clipVideo">'+esc(c.videoTitle)+'</div><div class="range">'+fmt(c.startTime)+' → '+fmt(c.endTime)+' <span class="duration">'+fmt(c.endTime-c.startTime)+'</span></div><div class="actions"><button data-play="'+c.id+'">▶ Play Loop</button><button data-del="'+c.id+'" class="del">Delete</button></div></article>').join('');$('empty').className=arr.length?'':'empty';if(!arr.length)$('empty').textContent=clips.length?'No matching clips.':'No clips yet.'}
const esc=x=>String(x).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
$('setStart').onclick=async()=>{try{let x=await msg({action:'GET_VIDEO_INFO'});$('start').value=fmt(x.currentTime);manual=true;toast('Start set')}catch{toast('Open YouTube first')}};$('setEnd').onclick=async()=>{try{let x=await msg({action:'GET_VIDEO_INFO'});$('end').value=fmt(x.currentTime);manual=true;toast('End set')}catch{toast('Open YouTube first')}};
$('save').onclick=save;$('refresh').onclick=info;$('search').oninput=render;$('sort').onchange=render;$('start').oninput=$('end').oninput=()=>manual=true;
$('list').onclick=async e=>{let p=e.target.closest('[data-play]'),d=e.target.closest('[data-del]');if(p){let c=clips.find(x=>x.id===p.dataset.play);if(!c)return;try{await msg({action:'START_CLIP_LOOP',startTime:c.startTime,endTime:c.endTime,clipId:c.id,targetVideoId:c.videoId});toast('Looping '+c.clipName)}catch{toast('Open the saved video first')}}if(d){clips=clips.filter(x=>x.id!==d.dataset.del);await chrome.storage.local.set({clips});render();toast('Clip deleted')}};
load().then(info);setInterval(info,1000);